# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aed2bada40f8b4f94dc2a26112593e07a52b80da896fe3424ea2a620aee3d968539382a9e6db829c965339a41fce1420fa4a3799a779aeb54d0fe73f498204fc

test:
  secret_key_base: 0d53844b642d88c3d6b266e0eafaf42140e94985c9d1d8fcdbd26b0fb34da762d2f38d71bfeef92609e861fbd3a2d9e8e78923d46376707b4730def62e01de2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
